# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

creasteSS_Rcpp <- function(lab, datx) {
    .Call('_hclda_creasteSS_Rcpp', PACKAGE = 'hclda', lab, datx)
}

computeY_Rcpp <- function(N, G, p, r, W, B, bar_x, barx, n_g) {
    .Call('_hclda_computeY_Rcpp', PACKAGE = 'hclda', N, G, p, r, W, B, bar_x, barx, n_g)
}

creasteSS_fast_Rcpp <- function(lab, datx, r) {
    .Call('_hclda_creasteSS_fast_Rcpp', PACKAGE = 'hclda', lab, datx, r)
}

loo_CLD_Rcpp <- function(test_dat, test_lab, train_dat, train_lab, r, N_press, bar_x, barx, xjxjT, W, S_x, sum_nj_xjbar_xjbar_T) {
    .Call('_hclda_loo_CLD_Rcpp', PACKAGE = 'hclda', test_dat, test_lab, train_dat, train_lab, r, N_press, bar_x, barx, xjxjT, W, S_x, sum_nj_xjbar_xjbar_T)
}

fast_loo_CLD_Rcpp <- function(p, cv, test_lab, test_dat, train_lab, hii, hat_Y_rowvec, Y_rowvec, alpha, ci_colvec, sum_hatY2, sum_hY_H_rowvec, sum_H2_double, sum_hatY_j, sum_H_j_i, bar_x, N_press, r) {
    .Call('_hclda_fast_loo_CLD_Rcpp', PACKAGE = 'hclda', p, cv, test_lab, test_dat, train_lab, hii, hat_Y_rowvec, Y_rowvec, alpha, ci_colvec, sum_hatY2, sum_hY_H_rowvec, sum_H2_double, sum_hatY_j, sum_H_j_i, bar_x, N_press, r)
}

cv_Rcpp <- function(datx, lab, r, N_press, SS_prime, type) {
    .Call('_hclda_cv_Rcpp', PACKAGE = 'hclda', datx, lab, r, N_press, SS_prime, type)
}

cv_clustering_Rcpp <- function(datx, lab, lab_for, r, N_press, SS_for, Cluster, type) {
    .Call('_hclda_cv_clustering_Rcpp', PACKAGE = 'hclda', datx, lab, lab_for, r, N_press, SS_for, Cluster, type)
}

